### PR TITLE
Enhanced Ui and added custom scroll bar

### LINKED ISSUE #42: UI Improvement
**Is your feature request related to a problem? Please describe.**
The UI is very plain and simple for now

**Describe the solution you'd like**
I would like to improve the look and UX of the website

**Describe alternatives you've considered**
Using custom libraries such as bootstrap can help

**Additional context**

### PR DESCRIPTION
**Pull request by Sa24miksha**
##DESCRIPTION 
This PR Enhances the entire UI of the website which includes :
- Better Color Gradient making the website aesthetic.
- [ADDED] Attractive fonts.
- [ADDED] Custom Scrollbar in the website and in the "Logs" box. 
1 file changed, 94 insertions(+), 39 deletions(-)

Fixes #42 

##How Has This Been Tested?
Tested the application after adding and improving the feature, and everything is working fine.

##Checklist
I have performed a self-review of my own code
My changes generate no new warnings
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes

##SCREENSHOTS : 
image
image
Screenshot (336)
Screenshot (335)

### CODE REVIEW

**Comment by Sa24miksha** [comment]
I have observed the website and improved the entire UI of the website efficiently, Please review my request.

**Comment by atapas** [comment]
Hi @Sa24miksha 

Thanks for putting the effort in changing the color schemes. I am unsure if we need all the changes for it as it has to be tested for accessibility. The current colors are accessible and tested. I would suggest you revert the changes and just fix these two things:

- In responsive mode, the border of the last box touches the log console.

image

- I liked the way you had styled the combobox. You can do that change but make sure it is redable in all the themes.
- 
image

Let me know if you are fine doing these changes.

**Comment by Sa24miksha** [comment]
> Hi @Sa24miksha
> 
> Thanks for putting the effort in changing the color schemes. I am unsure if we need all the changes for it as it has to be tested for accessibility. The current colors are accessible and tested. I would suggest you revert the changes and just fix these two things:
> 
> * In responsive mode, the border of the last box touches the log console.
> 
> image
> 
> * I liked the way you had styled the combobox. You can do that change but make sure it is redable in all the themes.
> 
> image
> 
> Let me know if you are fine doing these changes.

Yes @atapas sir , i will do these changes

**Comment by Sa24miksha** [comment]
@atapas sir i will do the changes can you please provide the exact dimensions of the responsive mode because i have checked in few and there it is working fine.
Also sir the combobox in readable in all the themes perfectly .

**Comment by Sa24miksha** [comment]
@atapas sir i will do the changes can you please provide the exact dimensions of the responsive mode because i have checked in few and there it is working fine. 
Screenshot 2023-10-10 144713

sir did you liked the custom scrollbar should we go with that? 
Screenshot 2023-10-06 193751

**Comment by atapas** [comment]
> @atapas sir i will do the changes can you please provide the exact dimensions of the responsive mode because i have checked in few and there it is working fine. Screenshot 2023-10-10 144713
> 
> sir did you liked the custom scrollbar should we go with that? Screenshot 2023-10-06 193751

Select the Promise.race

image

**Pull request merged**
