### PR TITLE
add hover effects to cards

### PR DESCRIPTION
**Pull request by kkartik07**
#20 Hi! I added some hover effects to the cards. Also made minor UI enhancements.
Please review and accept my PR.
Thanks.😃

### CODE REVIEW

**Review by atapas — CHANGES_REQUESTED** [review]
It's missing the background colors.

image

**Comment by kkartik07** [comment]
I didn't get you. I had added hover effects to the cards only (those 3 boxes).
Please clarify this.

**Comment by atapas** [comment]
> I didn't get you. I had added hover effects to the cards only (those 3 boxes). Please clarify this.

Once the promise resolves, it should've the color indications

image

**Comment by kkartik07** [comment]
I have made the required changes. Please review.
Thanks.

**Pull request closed without merging**
